type element = {
  AtomicNumber: string;
  Symbol: string;
  Name: string;
  AtomicMass: string;
  CPKHexColor: string;
  ElectronConfiguration: string;
  Electronegativity: string;
  AtomicRadius: string;
  IonizationEnergy: string;
  ElectronAffinity: string;
  OxidationStates: string;
  StandardState: string;
  MeltingPoint: string;
  BoilingPoint: string;
  Density: string;
  GroupBlock: string;
  YearDiscovered: string;
};

export const periodic_data = [
  {
    col1: {
      "AtomicNumber":"1",
      "Symbol":"H",
      "Name":"Hydrogen",
      "AtomicMass":"1.0080",
      "CPKHexColor":"FFFFFF",
      "ElectronConfiguration":"1s1",
      "Electronegativity":"2.2",
      "AtomicRadius":"120",
      "IonizationEnergy":"13.598",
      "ElectronAffinity":"0.754",
      "OxidationStates":"+1, -1",
      "StandardState":"Gas",
      "MeltingPoint":"13.81",
      "BoilingPoint":"20.28",
      "Density":"0.00008988",
      "GroupBlock":"Nonmetal",
      "YearDiscovered":"1766"
    },
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {
      "AtomicNumber":"2",
      "Symbol":"He",
      "Name":"Helium",
      "AtomicMass":"4.00260",
      "CPKHexColor":"D9FFFF",
      "ElectronConfiguration":"1s2",
      "Electronegativity":"",
      "AtomicRadius":"140",
      "IonizationEnergy":"24.587",
      "ElectronAffinity":"",
      "OxidationStates":"0",
      "StandardState":"Gas",
      "MeltingPoint":"0.95",
      "BoilingPoint":"4.22",
      "Density":"0.0001785",
      "GroupBlock":"Noble gas",
      "YearDiscovered":"1868"
    }
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  },
  {
    col1: {},
    col2: {},
    col3: {},
    col4: {},
    col5: {},
    col6: {},
    col7: {},
    col8: {},
    col9: {},
    col10: {},
    col11: {},
    col12: {},
    col13: {},
    col14: {},
    col15: {},
    col16: {},
    col17: {},
    col18: {}
  }
]
